controllers/CentrosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Centros;
use app\models\search\CentrosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\CentrosInformacion;
use app\models\CentrosAgendas;
use app\models\Cuentas;

/**
 * UsuariosController implements the CRUD actions for Usuarios model.
 */
class CentrosController extends Controller {

    /**
     * Lists all Usuarios models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new CentrosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Usuarios model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Usuarios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $modelCuenta = new Cuentas();

        if ($modelCuenta->load(Yii::$app->request->post())) {

            $password = Yii::$app->getSecurity()->generateRandomString(10);
            $modelCuenta->password = Yii::$app->getSecurity()->generatePasswordHash($password);

            if ($modelCuenta->save()) {
                $modelCentros = new Centros;
                $modelCentros->id = $modelCuenta->id;
                $modelCentros->username = $modelCuenta->username;
                $modelCentros->mail = $modelCuenta->mail;
                
                if ($modelCentros->save()) {
                    self::sendRegistrationMail($modelCentros, $password);
                    CentrosInformacion::createEmptyUserInformation($modelCentros->id);
                    CentrosAgendas::createAgenda($modelCentros->id, 'Agenda de ' . $modelCentros->username);

                    return $this->redirect(['view', 'id' => $modelCentros->id]);
                }
            }
            else {
                return $this->refresh();
            }
        } else {
            return $this->render('create', [
                        'model' => $modelCuenta,
            ]);
        }
    }

    /**
     * Updates an existing Usuarios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Usuarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Usuarios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Usuarios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Centros::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    private function sendRegistrationMail($model, $password) {

        $content = "<p> usuario: " . $model->username . "</p>";
        $content .= "<p> password: " . $password . "</p>";

        Yii::$app->mailer->compose("@app/mail/layouts/html.php", ["content" => $content])
                ->setTo($model->mail)
                ->setFrom(['vilellamunoz@gmail.com' => 'xavier vilella'])
                ->setSubject('usuario registrado')
                ->send();
    }

}

controllers/EmpleadosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Empleados;
use app\models\search\Empleados as EmpleadosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Cuentas;
use app\models\EmpleadosAgendas;

use app\models\EmpleadosHorarios;
/**
 * EmpleadosController implements the CRUD actions for Empleados model.
 */
class EmpleadosController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Empleados models.
     * @return mixed
     */
    public function actionIndex()
    {
        $queryParams = Yii::$app->request->queryParams;
        if(!isset($queryParams['Empleados'])){
            $filtros = ['Empleados'=>['id_centro'=>Yii::$app->user->id]];
        }else{
            $filtros = $queryParams;
            $filtros['Empleados']['id_centro'] = Yii::$app->user->id;
        }
        
        $searchModel = new EmpleadosSearch();
        $dataProvider = $searchModel->search($filtros);
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Empleados model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Empleados model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelEmpleados = new Empleados();

        if ($modelEmpleados->load(Yii::$app->request->post())) {
            
            $modelEmpleados->username = Yii::$app->user->identity->username.'.'.$modelEmpleados->username;
            $modelEmpleados->id_centro = Yii::$app->user->id ;
            
            $modelCuenta = new Cuentas();
            $modelCuenta->username = $modelEmpleados->username;
            $modelCuenta->rol_id = Cuentas::ROLE_USER;
            $modelCuenta->status = Cuentas::STATUS_ACTIVE;
            $password = Yii::$app->getSecurity()->generateRandomString(10);
            $modelCuenta->password = Yii::$app->getSecurity()->generatePasswordHash($password);

            if($modelCuenta->save()){
                $modelEmpleados->id_empleado = $modelCuenta->id;
                $modelEmpleados->save();
                
                self::sendRegistrationMail($modelEmpleados, $password);
                EmpleadosAgendas::createAgenda($modelEmpleados->id_empleado, 'Agenda de ' . $modelEmpleados->username);
                EmpleadosHorarios::createHorario($modelEmpleados->id_empleado);
                
                return $this->redirect(['view', 'id' => $modelEmpleados->id_empleado]);  
                
            }
            else{
                $this->refresh();
            }            
        } else {
            return $this->render('create', [
                'model' => $modelEmpleados,
            ]);
        }
    }

    /**
     * Updates an existing Empleados model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_empleado]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Empleados model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    
    /**
     * Updates an existing Empleados model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionHorario($id)
    {
        $model = EmpleadosHorarios::findHorarioByIdEmpleado($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('actualizarhorario', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Empleados model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Empleados the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Empleados::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
    private function sendRegistrationMail($model, $password) {

        $content = "<p> usuario: " . $model->username . "</p>";
        $content .= "<p> password: " . $password . "</p>";

        Yii::$app->mailer->compose("@app/mail/layouts/html.php", ["content" => $content])
                ->setTo($model->mail)
                ->setFrom(['vilellamunoz@gmail.com' => 'xavier vilella'])
                ->setSubject('usuario registrado')
                ->send();
    }
}

controllers/MainController.php
<?php

namespace app\controllers;

use Yii;
use app\models\EmpleadosAgendas;
use app\models\CentrosAgendas;
use app\models\Cuentas;
use app\models\EmpleadosHorarios;

class MainController extends BaseController {

    public function actionIndex() {
        
        $id = Yii::$app->request->get('id');
        
        if(isset($id)){
            $tipo = 'empleado';
            $agenda = EmpleadosAgendas::getAgendaByIdUser($id);
        }
        else{
            switch (Yii::$app->user->identity->rol_id){
                case Cuentas::ROLE_USER:
                    $tipo = 'empleado';
                    $agenda = EmpleadosAgendas::getAgendaByIdUser(Yii::$app->user->identity->id);
                    break;
                case Cuentas::ROLE_CENTRO:
                    $tipo = 'centro';
                    $agenda = CentrosAgendas::getAgendaByIdUser(Yii::$app->user->identity->id);
                    break;    
            }
        }
        
        return $this->render('index', ['agenda' => $agenda, 'tipo' => $tipo , 'id' => $id ]);
    }
    
    public function actionGetdatoscalendario(){
        $tipo = Yii::$app->request->post('tipo');
        $id = Yii::$app->request->post('id');
        switch ($tipo){
            case 'empleado':
                $businessHours = EmpleadosHorarios::getBusinessHours($id);
                break;
            case 'centro':
                break;
        }
        
        $json = json_encode(['businessHours'=>$businessHours]);
        
        echo $json;
    }

}

controllers/RolController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Rol;
use app\models\search\RolSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Operacion;

/**
 * RolController implements the CRUD actions for Rol model.
 */
class RolController extends BaseController {

    

    /**
     * Lists all Rol models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new RolSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rol model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rol model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Rol();
        $tipoOperaciones = Operacion::find()->all();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                        'model' => $model,
                        'tipoOperaciones' => $tipoOperaciones
            ]);
        }
    }

    /**
     * Updates an existing Rol model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);
        $tipoOperaciones = Operacion::find()->all();

        $model->operaciones = \yii\helpers\ArrayHelper::getColumn(
                        $model->getRolOperaciones()->asArray()->all(), 'operacion_id'
        );

        if ($model->load(Yii::$app->request->post())) {
            if (!isset($_POST['Rol']['operaciones'])) {
                $model->operaciones = [];
            }
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {

            return $this->render('update', [
                        'model' => $model,
                        'tipoOperaciones' => $tipoOperaciones
            ]);
        }
    }

    /**
     * Deletes an existing Rol model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rol model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rol the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Rol::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/layouts/partial/navAdmin.php
<?php

use yii\bootstrap\Nav;

echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
        [
            'label' => 'Administración',
            'items' => [
                '<li class="dropdown-header">Admin Centros</li>',
                ['label' => 'Centros', 'url' => ['/centros/index']],
                ['label' => 'Nuevo Usuario', 'url' => ['/centros/create']],
                ['label' => 'Información Centros', 'url' => ['/centrosinformacion/index']],
                ['label' => 'Nueva Información Centros', 'url' => ['/centrosinformacion/create']],
                '<li class="divider"></li>',
                '<li class="dropdown-header">Admin Roles</li>',
                ['label' => 'Roles', 'url' => ['/rol/index']],
                ['label' => 'Nuevo Rol', 'url' => ['/rol/create']],
                '<li class="divider"></li>',
                '<li class="dropdown-header">Admin Permisos</li>',
                ['label' => 'Permisos', 'url' => ['/operacion/index']],
                ['label' => 'Nuevo Permiso', 'url' => ['/operacion/create']],
            ],
        ],
        [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ],
    ],
]);

views/layouts/partial/navCentro.php
<?php

use app\models\CentrosAgendas;
use app\models\Empleados;
use yii\bootstrap\Nav;
use yii\helpers\Url;

$agenda = CentrosAgendas::getAgendaByIdUser(Yii::$app->user->identity->id);
$empleados = Empleados::getEmpleadosByIdCentro(Yii::$app->user->identity->id);
$items = [];

$items[] = ['label' => 'Agenda del Centro', 'url' => ['/main/index']];
$items[] = '<li class="divider"></li>';
$items[] = '<li class="dropdown-header">Agendas empleados</li>';
foreach($empleados as $empleado){
    $items[] = ['label' => $empleado->username, 'url' => Url::to(['main/index', 'id' => $empleado->id_empleado])];
}

echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
        [
            'label' => 'Agendas',
            'items' => $items
        ],
        [
            'label' => 'Empleados del Centro',
            'url' => ['/empleados/index'],
        ],
        [
            'label' => 'Datos del Centro',
            'items' => [
                ['label' => 'Datos Básicos', 'url' => ['/centrosinformacion/view']],
                ['label' => 'Actualizar Contraseña', 'url' => ['/centrosinformacion/actualizarpassword']],
            ],
        ],
        [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ],
    ],
]);

views/layouts/partial/navGuest.php
<?php

use yii\bootstrap\Nav;

echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            ['label' => 'Login', 'url' => ['/site/login']]
        ],
    ]);  

views/layouts/partial/navUser.php
<?php

use app\models\EmpleadosAgendas;
use yii\bootstrap\Nav;
use yii\helpers\Url;

$agenda = EmpleadosAgendas::getAgendaByIdUser(Yii::$app->user->identity->id);

echo Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'items' => [
        ['label' => 'Ver Agenda', 'url' => ['/main/index']],                
        [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ],
    ],
]);